### ISSUE TITLE
provide a flag to disable the logging of inbound and outbound messages

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#557]
#### Reason/Context
when there are multiple server and long messages are being sent back and forth, the log becomes unreadable due to tremendous amount of message logs. It would be great to have a flag in the config file so user can disable the message logs.

#### Description
I suggest we add an option to disable the logging.
something like:

> glee.config.js

```js
...

glee: {
  logInMessages: true/false
  logOutMessages: true/false
}
...
```

**Comment by fmvilas** [comment]
I'd add different levels of logging. For instance, the current one would be `extended` because it provides a bunch of info but we can add:

* `channel-only`: It just displays that a message has been sent/received on a given channel. No message, just a single line with the channel address and its ID maybe. Something like `↗ user_signedup`.
* `none`: It disables the log.

And I'd try to be consistent with the naming of "incoming" and "outgoing" messages, so the config file would become something like this:

```js
glee: {
  logs: {
    incoming: 'channel-only',
    outgoing: 'none'
  }
}
```

**Comment by KhudaDad414** [comment]
/progress 10
started working on the issue.

**Comment by KhudaDad414** [comment]
/progress 90
PR #598 is ready for review.
